version: '3.9'

services:

  # kafka:
  #   image: 'bitnami/kafka:3.5'
  #   container_name: kafka_container
  #   environment:
  #     KAFKA_ENABLE_KRAFT: yes
  #     KAFKA_CFG_NODE_ID: 1
  #     KAFKA_CFG_PROCESS_ROLES: controller,broker
  #     KAFKA_CFG_LISTENERS: PLAINTEXT://:9094,CONTROLLER://:9095
  #     KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.115:19094
  #     KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
  #     KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@pre_kafka_container:9093
  #     KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
  #     KAFKA_HEAP_OPTS: -Xmx512M -Xms256M
  #     KAFKA_KRAFT_CLUSTER_ID: aF3+zO7$wT1~yY1?cC7,qW
  #     ALLOW_PLAINTEXT_LISTENER: yes
  #     KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
  #     KAFKA_BROKER_ID: 1
  #   ports:
  #     - "19094:9094"
  #     - "19095:9095"
  #   volumes:
  #     - ./kafka/broker1:/bitnami/kafka:rw

  # kafka-ui:
  #   image: provectuslabs/kafka-ui:latest
  #   container_name: kafka-ui_container
  #   environment:
  #     KAFKA_CLUSTERS_0_NAME: local
  #     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka_container:9094
  #   ports:
  #     - "9090:8080"
  #   depends_on:
  #     - kafka

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crm
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: on-failure

  redis:
    image: redis:7.0
    container_name: redis_db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: on-failure

  crm.shopdevgo.com:
    container_name: go_backend_crm_shopdev
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - MYSQL_HOST=mysql_db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=crm
      - REDIS_HOST=redis_db
      - REDIS_PORT=6379
      - PORT=8002
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app-network
    ports:
      - "8008:8002"

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data: