// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/QuocHuannn/Go-to-Work/internal/controller"
	"github.com/QuocHuannn/Go-to-Work/internal/repo"
	"github.com/QuocHuannn/Go-to-Work/internal/service"
)

// Injectors from user.wire.go:

func initUserRouterHandler() (*controller.UserController, error) {
	userRepository := repo.NewUserRepository()
	iUserService := service.NewUserService(userRepository)
	userController := controller.NewUserController(iUserService)
	return userController, nil
}
