server:
  port: 8001
  mode: "dev"
mysql:
  host: localhost
  port: 3306
  username: root
  password: root
  dbname: crm
  maxIdleConns: 10
  maxOpenConns: 100
  connectTimeout: 3600
logger:
  log_level: debug
  file_log_name: "./storage/logs/dev.001.log"
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true
redis:
  host: localhost
  port: 6379
  password:
  database: 0


  